# Generated by Django 4.2.15 on 2024-09-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_sigup',
            name='Status',
            field=models.CharField(default='waiting', max_length=100),
            preserve_default=False,
        ),
    ]
